name: Tests push
run-name: Test is testing with pyest
on:
  push:
    branches:
      - main
  # pull_request:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        python-version: ["3.8"]
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-xvfb
          # pip install pytest-cov
          pip install -e .
      - name: Test with pytest
        run: |
          python3 -m pytest
